[package]
name = "lovely_env_logger"
version = "0.1.0" # don't forget to update html_root_url
description = "a visually lovely env_logger"
edition = '2021'
repository = "https://github.com/borisfaure/lovely-env-logger"
authors = ["Boris Faure <boris@fau.re>", "Sean McArthur <sean@seanmonstar>"]
license = "MIT/Apache-2.0"
categories = ["development-tools::debugging"]
keywords = ["log", "logger", "logging"]
readme = "README.md"

include = [
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "src/**/*"
]

[dependencies]
env_logger = "0.9"
log = "0.4"
